version: '3'
services:
  tcms:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tcms_app
    ports:
      - "8090:8080"
    environment:
      - MYSQL_HOST=tcms_db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=transport_company
      - MYSQL_USER=alex
      - MYSQL_PASSWORD=1234
    networks:
      - networkinternal
    depends_on:
      - tcmsdb
  tcmsdb:
    image: mysql
    container_name: tcms_db
    restart: always
    environment:
      - MYSQL_DATABASE=transport_company
      - MYSQL_USER=alex
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=1234
    networks:
      - networkinternal
networks:
  networkinternal: