spring:
  main:
    banner-mode: off

#  datasource:
#    url: ${DATASOURCE.URL}
#    username: ${DATASOURCE.USERNAME}
#    password: ${DATASOURCE.PASSWORD}
  datasource:
     url: jdbc:mysql://192.168.2.101:3306/transport_company
     username: alex
     password: 1234

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml

