spring:
  main:
    banner-mode: off

#  datasource:
#    url: ${DATASOURCE.URL}
#    username: ${DATASOURCE.USERNAME}
#    password: ${DATASOURCE.PASSWORD}

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:transport_company}
    username: ${MYSQL_USER:alex}
    password: ${MYSQL_PASSWORD:1234}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml

jwt:
  secret:
    access: qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w==
    refresh: zL1HB3Pch05Avfynovxrf/kpF9O2m4NCWKJUjEp27s9J2jEG3ifiKCGylaZ8fDeoONSTJP/wAzKawB8F9rOMNg==

management:
  endpoints:
    web:
      exposure:
        include: env, info, health
